# Generated by Django 3.0.2 on 2020-01-30 14:25

from django.db import migrations
import django_enum_choices.choice_builders
import django_enum_choices.fields
import strava_viz.api.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stravaactivity',
            name='activity_type',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('run', 'run'), ('ride', 'ride')], default=strava_viz.api.models.ActivityType['RUN'], enum_class=strava_viz.api.models.ActivityType, max_length=4),
        ),
    ]
