# Generated by Django 3.0.2 on 2020-01-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_stravaactivity_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stravaactivity',
            name='distance_meter',
            field=models.FloatField(),
        ),
    ]
