# Generated by Django 3.0.2 on 2020-02-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stravaactivity',
            name='average_heartrate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stravaactivity',
            name='average_speed',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stravaactivity',
            name='polyline',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
