# Generated by Django 3.0.3 on 2020-02-04 17:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_enum_choices.choice_builders
import django_enum_choices.fields
import strava_viz.app.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200203_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stravaactivity',
            name='activity_type',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('run', 'run'), ('ride', 'ride'), ('swim', 'swim')], default=strava_viz.app.models.ActivityType['RUN'], enum_class=strava_viz.app.models.ActivityType, max_length=4),
        ),
        migrations.AlterField(
            model_name='stravaactivity',
            name='average_heartrate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stravaactivity',
            name='average_speed',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stravaactivity',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 4, 17, 25, 41, 948831, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='stravaactivity',
            name='distance_meter',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stravaactivity',
            name='moving_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stravaactivity',
            name='polyline',
            field=models.TextField(default=''),
        ),
    ]
