# Generated by Django 3.0.3 on 2020-02-05 18:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200204_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stravaactivity',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 5, 18, 17, 48, 677294, tzinfo=utc)),
        ),
    ]
