# Generated by Django 3.0.3 on 2020-02-07 12:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200205_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stravaactivity',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 7, 12, 0, 18, 814185, tzinfo=utc)),
        ),
    ]
