# Generated by Django 3.0.3 on 2020-02-07 14:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200207_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stravaactivity',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 7, 14, 18, 11, 874504, tzinfo=utc)),
        ),
    ]
